name: Build (release)

on:
  push:
    branches: ["release"]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ "main", "release", "develop" ]

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  run-tests:
    uses: ./.github/workflows/unit-tests.yml
    with:
      python-version: 3.x
      
  # TODO: Build .exe instead of .zip
  build-artifact:
      needs: [ run-tests ]
      runs-on: ubuntu-latest
      steps:
        - name: Check out code
          uses: actions/checkout@v2
        
        - name: Build artifact
          run: |
            mkdir -p build
            echo "Building project artifact..."
            cp ./main.py ./build/src 
            cd build && zip -r project-artifact.zip . && cd ..
  
        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: project-artifact
            path: ./build/project-artifact.zip

  release-new-version:
    needs: [ build-artifact ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Configure Git user
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
  
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: project-artifact
  
      - name: Deploy artifact to GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Deploying to GitHub Releases..."
          LAST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v1.0.0")

          VERSION=$(echo "$LAST_TAG" | sed 's/^v//')
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          
          if [ "$MAJOR" -eq 1 ]; then
            NEW_MAJOR=2
            NEW_MINOR=0
            NEW_PATCH=0
          else
            NEW_MAJOR=$MAJOR
            NEW_MINOR=$((MINOR + 1))
            NEW_PATCH=0
          fi
          
          NEW_TAG="v$NEW_MAJOR.$NEW_MINOR.$NEW_PATCH"
          gh release create "$NEW_TAG" ./project-artifact.zip --title "Release $NEW_TAG"

  mark-as-ready:
    needs: [ release-new-version ]
    runs-on: ubuntu-latest
    if: ${{ !failure() && !cancelled() }}
    steps:
      - name: Echo success message
        run: |
          echo "All OK."
